export const ProducteData = [
  {
    id: 1,
    title: "iPhone 9",
    description: "An apple mobile which is nothing like apple",
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    images: [
      "https://cdn.pricebaba.com/prod/images/product/mobile/59168/apple-iphone-9-raw-1665199.jpg",
    ],
  },
  {
    id: 2,
    title: "Samsung Galaxy S21",
    description:
      "The latest in Samsung's Galaxy S series with powerful features",
    price: 799,
    discountPercentage: 10.5,
    rating: 4.8,
    stock: 50,
    brand: "Samsung",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    images: [
      "https://img.etimg.com/thumb/width-1200,height-1200,imgsize-234895,resizemode-75,msid-81612953/magazines/panache/samsung-galaxy-s21-review-smartphone-offers-flagship-level-performance-camera-and-design.jpg",
    ],
  },
  {
    id: 3,
    title: "OnePlus 9",
    description: "A high-performance smartphone with a stunning display",
    price: 729,
    discountPercentage: 8.0,
    rating: 4.7,
    stock: 30,
    brand: "OnePlus",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
    images: [
      "https://oasis.opstatics.com/content/dam/oasis/page/2021/new-navi/eu/pc/9WinterMist.png",
    ],
  },
  {
    id: 4,
    title: "Google Pixel 5",
    description: "Google's flagship phone with the best of Android",
    price: 699,
    discountPercentage: 5.0,
    rating: 4.6,
    stock: 40,
    brand: "Google",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    images: [
      "https://5.imimg.com/data5/SELLER/Default/2023/4/299966797/CX/BE/WK/4409539/1-250x250.jpg",
    ],
  },
  {
    id: 5,
    title: "Sony Xperia 1 II",
    description: "A smartphone designed for creators with a 4K display",
    price: 1199,
    discountPercentage: 15.0,
    rating: 4.5,
    stock: 20,
    brand: "Sony",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
    images: [
      "https://images-cdn.ubuy.co.in/63523741324889116a5bf7f8-sony-xperia-1-ii-xq-at52-5g-256gb-8gb.jpg",
    ],
  },
  {
    id: 6,
    title: "Nokia 8.3 5G",
    description: "A reliable 5G smartphone with a durable design",
    price: 649,
    discountPercentage: 7.5,
    rating: 4.4,
    stock: 60,
    brand: "Nokia",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/6/thumbnail.jpg",
    images: [
      "https://images-cdn.ubuy.co.in/65ab5946719a2460eb5f6425-nokia-8-3-5g-dark-blue-6-81-128gb.jpg",
    ],
  },
  {
    id: 7,
    title: "Huawei P40 Pro",
    description: "An advanced smartphone with excellent camera capabilities",
    price: 899,
    discountPercentage: 9.0,
    rating: 4.9,
    stock: 25,
    brand: "Huawei",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4-kZaerAJYyQjWRGY79aaoSWtraSh1GaoZg&s",
    ],
  },
];
