export const ProducteData = [
  {
    id: 1,
    title: "iPhone 9",
    description: "An apple mobile which is nothing like apple",
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    images: [
      "https://cdn.pricebaba.com/prod/images/product/mobile/59168/apple-iphone-9-raw-1665199.jpg",
    ],
  },
  {
    id: 2,
    title: "Samsung Galaxy S21",
    description:
      "The latest in Samsung's Galaxy S series with powerful features",
    price: 799,
    discountPercentage: 10.5,
    rating: 4.8,
    stock: 50,
    brand: "Samsung",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    images: [
      "https://images.samsung.com/is/image/samsung/p6pim/uk/feature/galaxy-s21-5g/galaxy-s21-5g_highlights_01.jpg",
    ],
  },
  {
    id: 3,
    title: "OnePlus 9",
    description: "A high-performance smartphone with a stunning display",
    price: 729,
    discountPercentage: 8.0,
    rating: 4.7,
    stock: 30,
    brand: "OnePlus",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
    images: [
      "https://image01.oneplus.net/eb8b7f8c2bd34e5f8a83a2d20c8b0d52.png",
    ],
  },
  {
    id: 4,
    title: "Google Pixel 5",
    description: "Google's flagship phone with the best of Android",
    price: 699,
    discountPercentage: 5.0,
    rating: 4.6,
    stock: 40,
    brand: "Google",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    images: ["https://store.google.com/product/pixel_5?hl=en"],
  },
  {
    id: 5,
    title: "Sony Xperia 1 II",
    description: "A smartphone designed for creators with a 4K display",
    price: 1199,
    discountPercentage: 15.0,
    rating: 4.5,
    stock: 20,
    brand: "Sony",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
    images: [
      "https://www.sony.co.uk/image/3e06f7f8a4bc0c64b519b879c4b07f7d?fmt=pjpeg&wid=2000&hei=2000",
    ],
  },
  {
    id: 6,
    title: "Nokia 8.3 5G",
    description: "A reliable 5G smartphone with a durable design",
    price: 649,
    discountPercentage: 7.5,
    rating: 4.4,
    stock: 60,
    brand: "Nokia",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/6/thumbnail.jpg",
    images: ["https://www.nokia.com/phones/en_int/nokia-8-3-5g"],
  },
  {
    id: 7,
    title: "Huawei P40 Pro",
    description: "An advanced smartphone with excellent camera capabilities",
    price: 899,
    discountPercentage: 9.0,
    rating: 4.9,
    stock: 25,
    brand: "Huawei",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
    images: [
      "https://consumer.huawei.com/content/dam/huawei-cbg-site/common/mkt/pdp/phones/p40-pro/p40pro-3.jpg",
    ],
  },
];
